# Generated by Django 5.2.3 on 2025-06-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_musclegroup_alter_exercise_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="set",
            unique_together={("logged_exercise", "set_number")},
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="sets",
        ),
        migrations.RemoveField(
            model_name="workoutexercise",
            name="weight",
        ),
        migrations.AddField(
            model_name="set",
            name="workout_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="workouts.workoutexercise",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="set",
            name="logged_exercise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="workouts.loggedexercise",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="set",
            unique_together={
                ("logged_exercise", "set_number"),
                ("workout_exercise", "set_number"),
            },
        ),
    ]
